README.md
This PR is meant to handle the requests set forth by @HelloDeadline in #11
=> #11 Added a 'Browser Support' section to the README

README.md
=> Fix README "10 lines" example

three.js/src/threex/threex-artoolkitsource.js, three.js/vendor/jsartoolkit5/js/artoolkit.api.js
changes on 2 functions to get correct rotation and aspect ratio of models in portrait mode
=> fixing portrait mode

ISSUE_TEMPLATE.md
inspired by webpack's issue template
=> Created Basic Issue Template

PULL_REQUEST_TEMPLATE.md
Initial version of the Pull Request template
=> Created PULL_REQUEST_TEMPLATE.md

aframe/build/aframe-ar.js, aframe/src/component-anchor.js
code was missing to use custom marker, this will use patternUrl as specified in the documentation.
=> fix custom marker

README.md
Content improvements
**Can it be referenced to an Issue? If so what is the issue number ?**
No
Check the ReadMe file
**Summary**
1. Added NPM, Gitter, twitter, patreon badges
2. Added an image at the top, removed Efficient from the title.
No
=> Added NPM, Gitter, twitter, patreon badges

README.md
fixed some grammar errors :-)
** Can it be referenced to an Issue? If so what is the issue # ?**
**Summary**
=> fixed some grammar issues :-) 

README.md
I hosted the image on one of my repo. I am not really sure where to put it in yours.
You should download it and add it in the repo.
=> Improxe UX for mobile use with a Qr Code

three.js/src/threex/threex-armarkercontrols.js
New feature, marker smoothing.
Original PR was #263, and this fixes #311.
**Summary**
Solves the AR experience constantly wiggling because of tiny changes in the marker tracking.
No.
This is not my code, the original PR was #263 by @ideolio. We just reimplemented it on a clean code base!
We may want to add a parameter for turning this off / changing settings via parameter instead of constants.
=> Implement marker tracking smoothing from @ideolio PR #263

README.md
=> Added an index

README.md
This PR add a link and a description about ar-gif, a new library that aims to make web AR with web components.
@nicolocarpignoli ask me in this [thread](https://github.com/jeromeetienne/AR.js/issues/469#issuecomment-470081039) for this update.
=> Add ar-gif to README.md

README.md
Changes ReadME
** Can it be referenced to an Issue? If so what is the issue # ?**
**Summary**
Looks like the usernames were changed. This resulted in the link being a dead end
=> Fixed dead link in Readme

README.md
Just adding two lines to the Status section of the Readme for the Gitter lobby and Trello board.
** Can it be referenced to an Issue? If so what is the issue # ?**
#506
Just click em. :-)
**Summary**
Nope
=> Adding links for Trello and Gitter to dev branch.

README.md, aframe/demos/demo-hatsune-miku/full-hatsune-original.html, aframe/demos/demo-hatsune-miku/old-full-hatsune.html, aframe/demos/demo-hatsune-miku/old-hatsune.html, three.js/examples/arcode.html
closes https://github.com/jeromeetienne/AR.js/issues/535
can someone test and give a quick look? it's just a find&replace.
=> Replace rawgit references with githack

three.js/README.md
bugfix
no
[Generate a custom marker](https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html) with a pattern ratio that is not 0.5
**Summary**
It doesn't work without this undocumented option and the [related docs](https://jeromeetienne.github.io/AR.js/three.js/) have typos in class names.
no
=> Update Three.js docs

aframe/examples/click-places/places.js, aframe/examples/places-name/places.js
closes https://github.com/jeromeetienne/AR.js/issues/609
=> WIP Fix load static load of places 

README.md, aframe/README.md
**⚠️ All PRs have to be done versus 'dev' branch, so be aware of that, or we'll close your issue ⚠️**
- Fix typos and grammatical errors.
- Update links.
No.
No testing required.
**Summary**
No.
**Please TEST your PR before proposing it. Specify here what device you have used for tests, version of OS and version of Browser**
=> Documentation edits on location-based AR

CHANGELOG.md, README.md
**⚠️ All PRs have to be done versus 'dev' branch, so be aware of that, or we'll close your issue ⚠️**
Just added a link to the browser support section of the readme file.
https://github.com/jeromeetienne/AR.js/issues/643
No test needed.
**Summary**
Solves nothing
No
**Please TEST your PR before proposing it. Specify here what device you have used for tests, version of OS and version of Browser**
=> Added the spreadsheet link in the readme file.

package.json
CDN enhancement
#728 
Go to https://www.jsdelivr.com/package/npm/ar.js and see if a default selection shows up.
**Summary**
See #728. Also will be used by web bundlers such as Webpack, Browserify, and Rollup.
No
**Please TEST your PR before proposing it. Specify here what device you have used for tests, version of OS and version of Browser**
N/A
N/A
=> Default package script for jsdelvr et al
